### ISSUE TITLE
request help: How to add proto file that import another proto file?（如何添加相互依赖的多个proto文件）

### ISSUE THREAD

**Issue by fregie** [apache/incubator-apisix#1469]
### Issue description
我有几个相互依赖的proto文件需要添加目录结构如下
├── boost
│   ├── accelConf
│   │   ├── accelConf.pb.go
│   │   └── accelConf.proto
│   ├── boost.pb.go
│   └── boost.proto
├── code
│   ├── code.pb.go
│   └── code.proto
├── go.mod
├── go.sum
├── line_manager
│   ├── line_manager.pb.go
│   └── line_manager.proto
├── README.md
└── util
    ├── util.pb.go
    └── util.proto

我把几个proto文件都按照文档添加了，但是添加后访问出现这样的报错:
```
2020/04/17 08:31:48 [error] 24#24: *140709 lua entry thread aborted: runtime error: /usr/local/apisix//deps/share/lua/5.1/protoc.lua:283: module load error: proto/boost/boost.proto
	./proto/boost/boost.proto: No such file or directory
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/local/apisix//deps/share/lua/5.1/protoc.lua:283: in function 'parsefile'
	/usr/local/apisix//deps/share/lua/5.1/protoc.lua:447: in function 'top_parser'
	/usr/local/apisix//deps/share/lua/5.1/protoc.lua:771: in function 'f'
	/usr/local/apisix//deps/share/lua/5.1/protoc.lua:1028: in function 'do_compile'
	/usr/local/apisix//deps/share/lua/5.1/protoc.lua:1032: in function 'compile'
	/usr/local/apisix//deps/share/lua/5.1/protoc.lua:1042: in function 'load'
	...local/apisix/lua/apisix/plugins/grpc-transcode/proto.lua:46: in function 'create_obj_fun'
	/usr/local/apisix/lua/apisix/core/lrucache.lua:64: in function 'fetch'
	/usr/local/apisix/lua/apisix/plugins/grpc-transcode.lua:98: in function 'phase_fun'
	/usr/local/apisix/lua/apisix.lua:129: in function 'run_plugin'
	/usr/local/apisix/lua/apisix.lua:411: in function 'grpc_access_phase'
	access_by_lua(nginx.conf:206):2: in main chunk, client: 127.0.0.1, server: , request: "GET /api/2/line HTTP/1.1", host: "127.0.0.1:9080"
```
看得出这是在编译proto文件时找不到依赖的其他proto文件导致的，那么如何才能解决这个问题呢？

### Environment

* apisix version (cmd: `apisix version`): 1.1
* OS: centos7

**Comment by moonming** [comment]
@nic-chen please take a look.

**Comment by nic-chen** [comment]
建议你先手动合并proto依赖的字段。
这个问题解决起来还是挺麻烦，我目前想到两种方法：
1、描述好依赖关系，加载的时候把依赖的proto一起加载
这个方法的难点在于怎么把依赖关系描述好，因为咱们用的不是关系型数据库，所以这里要思考一下。
2、一次性把全部proto加载
这个实现不太好，而且有增量内容也不好处理。

如果你有好的想法欢迎分享或者提交pr~



It is recommended that you could manually merge the fields that proto depends on for now.

This issue is quite troublesome to solve, I currently think of two methods:
1. Describe the dependencies and load the dependent protos together when loading
The difficulty of this method is how to describe the dependencies, because we are not using a relational database, so we have to think about it here.
2. Load all protos at once
This implementation is not very good, and the incremental content is not easy to handle.

If you have good ideas, please share or pr ~
